# %% [markdown]
# # Japan Special Situations — Exploratory Analysis
#
# Diagnostic notebook, not a predictive model. Purpose: characterize the
# 62-case corpus and the inputs to the existing similarity engine
# (`src/cluster/precedent_engine.py`) so that Part 2's cluster/weight
# design (see `docs/Roadmap.md`) starts from evidence, not intuition alone.
#
# No weights or clustering logic are changed here. Outcome cross-tabs are
# descriptive context (case-law "what happened," not a success model) —
# see `Claude.md` for why this project deliberately avoids predictive framing.
#
# Runs standalone in Google Colab (`# %%` cells open as a notebook) or as a
# plain script (`python notebooks/exploratory_analysis.py`).

# %%
import itertools
import json
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt

pd.set_option('display.max_colwidth', 120)

# %% [markdown]
# ## Load data
# Tries common repo-relative paths first (works locally and in Colab with
# the repo cloned); falls back to a manual upload in a fresh Colab session.

# %%
def load_data() -> pd.DataFrame:
    # canonical file first (Part 1 output); archived 62-row snapshot second
    for path in (Path('japan-ma/data/Japan.csv'), Path('../japan-ma/data/Japan.csv'),
                 Path('data/Japan.csv'), Path('../data/Japan.csv'), Path('Japan.csv')):
        if path.exists():
            return pd.read_csv(path, encoding='utf-8-sig')
    try:
        from google.colab import files
        print('Japan.csv not found locally — please upload it.')
        uploaded = files.upload()
        return pd.read_csv(next(iter(uploaded)), encoding='utf-8-sig')
    except ImportError:
        raise FileNotFoundError(
            'Japan.csv not found. Run from the repo root or notebooks/, or upload manually in Colab.'
        )


df = load_data()
n = len(df)
print(f'Loaded {n} rows, {len(df.columns)} columns')

# %% [markdown]
# ## Shared helpers
# Small utilities mirroring `src/explore.py` and `src/cluster/precedent_engine.py`,
# duplicated here (not imported) so this notebook stays a single portable
# file that runs standalone in Colab without the rest of the repo present.

# %%
def blank(v) -> bool:
    """Mirrors precedent_engine.py's blank(): True if unusable for a feature match."""
    if pd.isna(v):
        return True
    if isinstance(v, str) and v.strip() in ('', 'nan', 'Unclear/TBV', 'Other'):
        return True
    return False


def discover_prefixed_group(df: pd.DataFrame, prefix: str) -> list:
    return [c for c in df.columns if c.startswith(prefix)]


ACTIVIST_COLUMNS = discover_prefixed_group(df, 'activist_')
ALL_PAIRS = list(itertools.combinations(range(n), 2))

# These mirror the feature sets `precedent_engine.py` currently scores on —
# referenced by name here (unlike src/explore.py's dynamic discovery)
# because the point of this section is to audit that specific engine.
CATEGORICAL_FEATURES = [
    'category_group', 'industry_group', 'board_recommendation_code',
    'competing_bid_flag', 'special_committee_flag', 'recurring_acquirer_flag',
    'outcome_code', 'squeeze_out_mechanism_code',
]
BOOLEAN_FEATURES = [
    'structure_has_TOB', 'structure_has_MBO', 'structure_has_squeeze_out',
    'structure_has_merger', 'structure_has_scheme', 'has_activist_involvement',
    'acquirer_is_unlisted', 'has_JFTC', 'has_CFIUS', 'has_METI', 'has_FEFTA',
    'has_China_SAMR', 'has_EU_regulator', 'has_DOJ_FTC_HSR', 'has_FIRB',
]


def conclusion_rate_by(df: pd.DataFrame, group_col: str, min_n_flag: int = 10) -> pd.DataFrame:
    """Descriptive conclusion-rate table: Concluded / (Concluded + Failed) per group.

    Other/Unclear rows are shown in their own column and excluded from the
    rate's denominator — never silently folded into "not a success" (see
    Section 1 for the corpus-wide Other/Unclear footnote). Groups with
    n < min_n_flag are explicitly flagged rather than presented as if
    reliable.
    """
    rows = []
    for group_val, sub in df.groupby(group_col, dropna=False):
        concluded = (sub['outcome_code'] == 'Concluded').sum()
        failed = (sub['outcome_code'] == 'Failed').sum()
        other = (sub['outcome_code'] == 'Other/Unclear').sum()
        denom = concluded + failed
        rate = concluded / denom if denom else float('nan')
        rows.append({
            group_col: group_val,
            'n': len(sub),
            'concluded': concluded,
            'failed': failed,
            'other_unclear': other,
            'conclusion_rate_excl_unclear': round(rate, 2) if denom else None,
            'flag_small_n': 'yes' if len(sub) < min_n_flag else '',
        })
    return pd.DataFrame(rows).sort_values('n', ascending=False).reset_index(drop=True)


# %% [markdown]
# ## 0. Data quality recap
# Full detail lives in `output/reports/data_quality.md` (generated by
# `src/explore.py`); this is a condensed inline version so the notebook
# is self-contained.

# %%
def estimate_pairs(df: pd.DataFrame) -> list:
    pairs = []
    for col in df.columns:
        if col.endswith('_is_estimate'):
            base = col[: -len('_is_estimate')]
            value_col = base if base in df.columns else f'{base}_value'
            pairs.append((value_col if value_col in df.columns else None, col))
    return pairs


quality_rows = []
for value_col, flag_col in estimate_pairs(df):
    if value_col is None:
        continue
    present = df[value_col].notna()
    pct_missing = 100 * (1 - present.mean())
    pct_estimate = (100 * df.loc[present, flag_col].fillna(False).astype(bool).mean()
                     if present.sum() else float('nan'))
    quality_rows.append({'field': value_col, 'pct_missing': round(pct_missing),
                          'pct_estimate_of_present': round(pct_estimate)})

data_quality_df = pd.DataFrame(quality_rows)
data_quality_df

# %%
df['verification_confidence_code'].value_counts(dropna=False)


# %% [markdown]
# ## 1. Outcome distribution (context, not a predictive target)
# Concluded / Failed / Other-Unclear counts. Other/Unclear rows are never
# folded into a failure rate anywhere in this notebook — shown separately,
# with examples, per project convention.

# %%
outcome_counts = df['outcome_code'].value_counts(dropna=False)
print(outcome_counts)

other_unclear = df[df['outcome_code'] == 'Other/Unclear']
pct_other = 100 * len(other_unclear) / n
print(f"\n{pct_other:.0f}% of cases are Other/Unclear — excluded from every "
      f"conclusion-rate denominator below.")
print(f"Examples: {other_unclear['target_full_name'].head(3).tolist()}")

outcome_counts.plot(kind='bar', title=f'Outcome distribution (n={n})', color='#4C72B0')
plt.tight_layout()
plt.show()


# %% [markdown]
# ## 2. Outcome cross-tabs (descriptive only, no significance testing)
# Every table uses `conclusion_rate_by`; the `other_unclear` column shows
# per-group composition, and `flag_small_n` marks groups under n=10 rather
# than presenting a rate as if it were reliable at any sample size.

# %%
print('--- Outcome by deal-structure mechanism ---')
for col in discover_prefixed_group(df, 'structure_has_'):
    print(f'\n{col}:')
    print(conclusion_rate_by(df, col))

# %%
print('--- Outcome by category_group ---')
conclusion_rate_by(df, 'category_group')

# %%
print('--- Outcome by regulator involvement ---')
df['any_foreign_regulator'] = df[
    ['has_CFIUS', 'has_FEFTA', 'has_China_SAMR', 'has_EU_regulator', 'has_FIRB', 'has_DOJ_FTC_HSR']
].any(axis=1)
for col in discover_prefixed_group(df, 'has_') + ['any_foreign_regulator']:
    print(f'\n{col}:')
    print(conclusion_rate_by(df, col))

# %%
print('--- Outcome by competing-bid flag ---')
conclusion_rate_by(df, 'competing_bid_flag')

# %%
print('--- Outcome by activist involvement ---')
conclusion_rate_by(df, 'has_activist_involvement')

# %%
print('--- Cross-border cut (category_group == "Cross-border outbound") ---')
df['is_cross_border'] = df['category_group'] == 'Cross-border outbound'
conclusion_rate_by(df, 'is_cross_border')


# %% [markdown]
# ## 3. Feature discriminativeness / rarity (feeds Part 2 weight review)
# For each feature `precedent_engine.py` currently scores on, how rare vs.
# common is it? This is the empirical basis for that engine's own stated
# logic ("rare, strong signal" vs "near-universal, weak signal") — lets us
# check whether hand-set weights track rarity. Weights are NOT changed
# here; that stays a Part 2 decision.

# %%
def boolean_rarity(df: pd.DataFrame, cols: list) -> pd.DataFrame:
    rows = []
    for col in cols:
        as_bool = df[col].fillna(False).astype(bool)
        rows.append({'feature': col, 'pct_true': round(100 * as_bool.mean()), 'n_true': int(as_bool.sum())})
    return pd.DataFrame(rows).sort_values('pct_true').reset_index(drop=True)


boolean_rarity(df, BOOLEAN_FEATURES + ACTIVIST_COLUMNS)

# %%
def categorical_concentration(df: pd.DataFrame, cols: list) -> pd.DataFrame:
    rows = []
    for col in cols:
        usable = df[col].apply(lambda v: not blank(v))
        vc = df.loc[usable, col].value_counts()
        top_share = vc.iloc[0] / vc.sum() if len(vc) else float('nan')
        rows.append({
            'feature': col, 'n_usable': int(usable.sum()), 'n_distinct_values': len(vc),
            'top_value': vc.index[0] if len(vc) else None,
            'top_value_share_pct': round(100 * top_share) if len(vc) else None,
        })
    return pd.DataFrame(rows).sort_values('top_value_share_pct').reset_index(drop=True)


categorical_concentration(df, CATEGORICAL_FEATURES)


# %% [markdown]
# ## 4. Feature co-occurrence / redundancy
# Jaccard similarity between boolean flags: if two features almost always
# co-occur, giving both independent weight in the similarity score
# double-counts one underlying signal. Pairs where either feature is true
# in fewer than 3 rows are excluded — co-occurrence on 1-2 rows is noise.

# %%
def jaccard(a: pd.Series, b: pd.Series) -> float:
    a, b = a.fillna(False).astype(bool), b.fillna(False).astype(bool)
    union = (a | b).sum()
    return (a & b).sum() / union if union else float('nan')


def top_cooccurring_pairs(df: pd.DataFrame, cols: list, min_support: int = 3, top_n: int = 20) -> pd.DataFrame:
    rows = []
    for c1, c2 in itertools.combinations(cols, 2):
        n1 = df[c1].fillna(False).astype(bool).sum()
        n2 = df[c2].fillna(False).astype(bool).sum()
        if n1 < min_support or n2 < min_support:
            continue
        j = jaccard(df[c1], df[c2])
        if j > 0:
            rows.append({'feature_a': c1, 'feature_b': c2, 'jaccard': round(j, 2), 'n_a': int(n1), 'n_b': int(n2)})
    return pd.DataFrame(rows).sort_values('jaccard', ascending=False).head(top_n).reset_index(drop=True)


top_cooccurring_pairs(df, BOOLEAN_FEATURES + ACTIVIST_COLUMNS)


# %% [markdown]
# ## 5. Pairwise comparability coverage
# `precedent_engine.py` only scores a feature match when BOTH rows in a
# pair are usable on it. Boolean flags (`has_*`/`structure_has_*`/
# `activist_*`) are always populated (False when absent) so their coverage
# is trivially 100% — the categorical features are where coverage loss
# actually happens, since `blank()` treats NaN/"Unclear/TBV"/"Other" as
# unusable.

# %%
def pairwise_categorical_coverage(df: pd.DataFrame, cols: list, pairs: list) -> pd.DataFrame:
    rows = []
    for col in cols:
        usable = df[col].apply(lambda v: not blank(v))
        both_usable = sum(1 for i, j in pairs if usable.iloc[i] and usable.iloc[j])
        rows.append({
            'feature': col, 'n_usable_rows': int(usable.sum()),
            'pct_pairs_both_usable': round(100 * both_usable / len(pairs)),
        })
    return pd.DataFrame(rows).sort_values('pct_pairs_both_usable').reset_index(drop=True)


pairwise_categorical_coverage(df, CATEGORICAL_FEATURES, ALL_PAIRS)


# %% [markdown]
# ## 6. Existing similarity-graph diagnostics
# Descriptive structure checks on the graph `src/cluster/precedent_engine.py`
# already produces (`output/precedent_graph_data.json`) — no engine changes
# here, just characterizing what `TOP_K=4` / `MIN_SCORE=1.5` currently yield.
# Run `python src/cluster/precedent_engine.py` first if this file is missing.

# %%
def load_graph_data() -> dict:
    for path in (Path('output/precedent_graph_data.json'), Path('../output/precedent_graph_data.json')):
        if path.exists():
            return json.loads(path.read_text(encoding='utf-8'))
    raise FileNotFoundError(
        'precedent_graph_data.json not found — run src/cluster/precedent_engine.py first.'
    )


graph = load_graph_data()
edges, nodes = graph['edges'], graph['nodes']

degree = pd.Series(0, index=[node['id'] for node in nodes])
for e in edges:
    degree[e['source']] += 1
    degree[e['target']] += 1

print('Degree distribution (edges touching each node):')
print(degree.value_counts().sort_index())
print(f"\nNodes with fewer than 4 links (fewer than TOP_K neighbors found above MIN_SCORE): {(degree < 4).sum()}")
print('\nTop 5 highest-degree ("hub") nodes:')
print(degree.sort_values(ascending=False).head())

# %%
scores = pd.Series([e['score'] for e in edges])
scores.plot(kind='hist', bins=20, title='Edge score distribution', color='#55A868')
plt.axvline(1.5, color='red', linestyle='--', label='MIN_SCORE=1.5')
plt.legend()
plt.tight_layout()
plt.show()
scores.describe()


# %% [markdown]
# ## Lens 1 — Legitimacy-of-consent axis
# `board_recommendation_code`: For → Engaged/Mixed → Opposed. The single
# most useful axis in the current Japan market post-METI-2023-guidelines.

# %%
df['board_recommendation_code'].value_counts(dropna=False).plot(
    kind='barh', title='Consent axis: board recommendation', color='#4C72B0')
plt.tight_layout()
plt.show()
conclusion_rate_by(df, 'board_recommendation_code')


# %% [markdown]
# ## Lens 2 — Price-discovery mechanism axis
# Single negotiated price (no bump) vs. genuine bidding war vs.
# MBO-then-interloper. Check: do bumps cluster where the board itself was
# split ("Mixed")?

# %%
pd.crosstab(df['board_recommendation_code'], df['price_was_bumped'])

# %%
pd.crosstab(df['structure_has_MBO'], df['competing_bid_flag'])


# %% [markdown]
# ## Lens 3 — Regulatory friction axis
# Pure-domestic (JFTC-only or fewer) vs. multi-jurisdiction. `num_regulators`
# is already a direct source-derived field.

# %%
df['multi_jurisdiction'] = df['num_regulators'] >= 2
pd.crosstab(df['category_group'], df['multi_jurisdiction'])

# %%
df['num_regulators'].value_counts().sort_index().plot(
    kind='bar', title='Number of regulators touched', color='#4C72B0')
plt.tight_layout()
plt.show()


# %% [markdown]
# ## Lens 4 — Precedent-value axis
# `notes_raw` / `key_debate_points_raw` are the richest fields for "what
# did this deal establish." No summarization/generation here — a
# mechanical keyword flag mirroring the existing `structure_has_*`
# convention, plus the raw text itself for cases worth reading in full.

# %%
PRECEDENT_KEYWORDS = ['first', 'template', 'precedent', 'proof-of-concept', 'landmark', 'signature']


def flags_precedent_setting(text) -> bool:
    if pd.isna(text):
        return False
    text = text.lower()
    return any(kw in text for kw in PRECEDENT_KEYWORDS)


df['notes_flags_precedent_setting'] = df['notes_raw'].apply(flags_precedent_setting)
print(f"{df['notes_flags_precedent_setting'].sum()} of {n} cases flagged as precedent-setting "
      f"language in notes_raw (keyword match: {PRECEDENT_KEYWORDS})")
df.loc[df['notes_flags_precedent_setting'], ['deal_id', 'target_full_name', 'notes_raw']]


# %% [markdown]
# ## Lens 5 — Instigator-identity axis
# Who actually drove the deal: activist-instigated vs. sponsor-instigated
# (PE/consortium) vs. strategic-instigated.

# %%
def instigator_type(row) -> str:
    if row['category_group'] == 'Activist campaign' or row['has_activist_involvement']:
        return 'Activist-instigated'
    if row['acquirer_is_unlisted'] or row['category_group'] == 'Take-private / MBO':
        return 'Sponsor-instigated'
    return 'Strategic-instigated'


df['instigator_type'] = df.apply(instigator_type, axis=1)
conclusion_rate_by(df, 'instigator_type')


# %% [markdown]
# ## Lens 6 — Deal-certainty / lock-up axis
# How "pre-wired" a deal was before announcement: toehold/irrevocables,
# special-committee process, and repeat-acquirer relationship, combined
# into a simple 0-3 signal count.

# %%
df['lockup_signal_count'] = (
    df['toehold_present_flag'].fillna(False).astype(bool).astype(int)
    + (df['special_committee_flag'] == 'Yes').astype(int)
    + (df['recurring_acquirer_flag'] == 'Yes').astype(int)
)
df['lockup_signal_count'].value_counts().sort_index().plot(
    kind='bar', title='Deal-certainty signal count (0-3)', color='#4C72B0')
plt.tight_layout()
plt.show()
conclusion_rate_by(df, 'lockup_signal_count')


# %% [markdown]
# ## Lens 8 — Activist "signature" axis
# Not just whether an activist was involved, but which fund(s) and in what
# combination — a solo Effissimo campaign reads differently from a
# Toshiba-style multi-fund coalition. Builds on Section 4's co-occurrence
# view, specialized to named activists.

# %%
def activist_signature(row) -> str:
    funds = [c.replace('activist_', '').replace('_', ' ') for c in ACTIVIST_COLUMNS if row[c]]
    return ', '.join(sorted(funds)) if funds else None


df['activist_signature'] = df.apply(activist_signature, axis=1)
df['activist_signature'].value_counts()


# %% [markdown]
# ## Summary
# This notebook is diagnostic, not decision-making: it characterizes the
# corpus and the existing similarity engine's inputs so Part 2's
# cluster/weight redesign (see `docs/Roadmap.md`) starts from evidence.
# No weights or clustering logic are changed here.
