"""
explore.py -- Part 1: data exploration & visualization for Japan.csv.

Design goal: keep working if Japan.csv's columns change shape (renamed,
added, removed) rather than assuming a fixed 128-column schema.

Two techniques make this adaptive:
  1. Column discovery by naming convention. Related columns (has_*
     regulators, activist_* named funds, structure_has_* mechanisms,
     mentions_* legal-basis flags, *_is_estimate paired fields) are found
     by prefix/suffix pattern match, per the conventions documented in
     docs/Japan_User_Guide.md -- not by an enumerated column list. Adding
     a new regulator/activist/mechanism column is picked up automatically.
  2. Guarded anchor columns. A short list of columns used for the core
     charts is referenced by name, but every use checks `col in df.columns`
     first -- a missing/renamed anchor column skips that one chart with a
     warning instead of crashing the whole run.

Usage:
    python src/explore.py [--input data/Japan.csv] [--output-dir output/]
"""
import argparse
import warnings
from pathlib import Path

import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

REPO_ROOT = Path(__file__).resolve().parents[1]

# Anchor columns for the core charts -- referenced by name, but every use
# below checks for presence first, so a schema change degrades gracefully.
ANCHOR_COLUMNS = [
    'deal_id', 'date_announced_year', 'category_group', 'industry_group',
    'outcome_code', 'verification_confidence_code', 'deal_size_usd_mn',
]


def load_data(input_path: Path) -> pd.DataFrame:
    df = pd.read_csv(input_path, encoding='utf-8-sig')
    missing_anchors = [c for c in ANCHOR_COLUMNS if c not in df.columns]
    if missing_anchors:
        warnings.warn(
            f"Anchor column(s) not found, related charts will be skipped: {missing_anchors}"
        )
    return df


def discover_prefixed_group(df: pd.DataFrame, prefix: str) -> list:
    """Boolean-flag columns sharing a naming-convention prefix, e.g. 'has_', 'activist_'."""
    return [c for c in df.columns if c.startswith(prefix)]


def discover_estimate_pairs(df: pd.DataFrame) -> list:
    """Every '<field>_is_estimate' column paired with its corresponding value column."""
    pairs = []
    for col in df.columns:
        if col.endswith('_is_estimate'):
            base = col[: -len('_is_estimate')]
            value_col = base if base in df.columns else f'{base}_value'
            pairs.append((base, value_col if value_col in df.columns else None, col))
    return pairs


# ---------------------------------------------------------------
# Data quality report
# ---------------------------------------------------------------
def build_data_quality_report(df: pd.DataFrame) -> str:
    n = len(df)
    lines = [
        '# Data Quality Report',
        '',
        f'Generated by `src/explore.py` against `{n}` rows.',
        '',
        '## Field completeness & estimate flags',
        '',
        'Every `<field>_is_estimate` column found in the data is checked against its paired value column.',
        '',
        '| Field | % missing | % of present values flagged as estimate |',
        '|---|---|---|',
    ]

    for base, value_col, flag_col in discover_estimate_pairs(df):
        if value_col is None:
            continue
        present = df[value_col].notna()
        pct_missing = 100 * (1 - present.mean())
        if present.sum() > 0:
            pct_estimate = 100 * df.loc[present, flag_col].fillna(False).astype(bool).mean()
        else:
            pct_estimate = float('nan')
        lines.append(f'| `{value_col}` | {pct_missing:.0f}% | {pct_estimate:.0f}% |')

    lines += ['', '## Verification confidence breakdown', '']
    if 'verification_confidence_code' in df.columns:
        counts = df['verification_confidence_code'].value_counts(dropna=False)
        for label, count in counts.items():
            label = label if pd.notna(label) else '(blank)'
            lines.append(f'- **{label}**: {count} row(s)')
    else:
        lines.append('_Column `verification_confidence_code` not found -- skipped._')

    lines += ['', '## High-cardinality raw-text columns (>80% unique values)', '']
    lines.append('Flags columns where near-every row has a distinct value -- a signal to group/model on '
                  'a coarser `_group`/`_code` column instead (see `docs/Japan_User_Guide.md`).')
    lines.append('')
    flagged_any = False
    for col in df.columns:
        if not col.endswith('_raw'):
            continue
        non_null = df[col].dropna()
        if len(non_null) == 0:
            continue
        uniqueness = non_null.nunique() / len(non_null)
        if uniqueness > 0.8:
            flagged_any = True
            lines.append(f'- `{col}`: {uniqueness:.0%} unique ({non_null.nunique()}/{len(non_null)} rows)')
    if not flagged_any:
        lines.append('_None found above the 80% threshold._')

    return '\n'.join(lines) + '\n'


# ---------------------------------------------------------------
# Visualizations
# ---------------------------------------------------------------
def save_bar_chart(series: pd.Series, title: str, out_path: Path, horizontal: bool = False):
    counts = series.value_counts(dropna=True).sort_values(ascending=horizontal)
    if counts.empty:
        warnings.warn(f"No data for '{title}', skipping chart.")
        return
    fig, ax = plt.subplots(figsize=(8, max(4, 0.4 * len(counts))) if horizontal else (8, 5))
    if horizontal:
        ax.barh(counts.index.astype(str), counts.values, color='#4C72B0')
    else:
        ax.bar(counts.index.astype(str), counts.values, color='#4C72B0')
        plt.xticks(rotation=45, ha='right')
    ax.set_title(title)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def make_visualizations(df: pd.DataFrame, figures_dir: Path):
    figures_dir.mkdir(parents=True, exist_ok=True)

    if 'date_announced_year' in df.columns:
        save_bar_chart(df['date_announced_year'], 'Deals per year', figures_dir / 'deals_per_year.png')

    if 'category_group' in df.columns:
        save_bar_chart(df['category_group'], 'Deals by category group', figures_dir / 'category_group.png', horizontal=True)

    if 'industry_group' in df.columns:
        save_bar_chart(df['industry_group'], 'Deals by industry group', figures_dir / 'industry_group.png', horizontal=True)

    if 'outcome_code' in df.columns:
        save_bar_chart(df['outcome_code'], 'Outcome distribution', figures_dir / 'outcome.png')

    if 'verification_confidence_code' in df.columns:
        save_bar_chart(df['verification_confidence_code'], 'Verification confidence',
                        figures_dir / 'verification_confidence.png', horizontal=True)

    # Dynamically discovered groups -- adapt automatically to new columns.
    regulator_cols = discover_prefixed_group(df, 'has_')
    if regulator_cols:
        counts = pd.Series({c.replace('has_', ''): df[c].fillna(False).astype(bool).sum() for c in regulator_cols})
        counts = counts[counts > 0].sort_values()
        if not counts.empty:
            fig, ax = plt.subplots(figsize=(8, max(4, 0.4 * len(counts))))
            ax.barh(counts.index.astype(str), counts.values, color='#55A868')
            ax.set_title('Regulator involvement (dynamically discovered has_* columns)')
            fig.tight_layout()
            fig.savefig(figures_dir / 'regulator_involvement.png', dpi=150)
            plt.close(fig)

    activist_cols = discover_prefixed_group(df, 'activist_')
    if activist_cols:
        counts = pd.Series({c.replace('activist_', '').replace('_', ' '): df[c].fillna(False).astype(bool).sum()
                             for c in activist_cols})
        counts = counts[counts > 0].sort_values()
        if not counts.empty:
            fig, ax = plt.subplots(figsize=(8, max(4, 0.4 * len(counts))))
            ax.barh(counts.index.astype(str), counts.values, color='#C44E52')
            ax.set_title('Named-activist frequency (dynamically discovered activist_* columns)')
            fig.tight_layout()
            fig.savefig(figures_dir / 'activist_frequency.png', dpi=150)
            plt.close(fig)

    structure_cols = discover_prefixed_group(df, 'structure_has_')
    if structure_cols:
        counts = pd.Series({c.replace('structure_has_', ''): df[c].fillna(False).astype(bool).sum()
                             for c in structure_cols})
        counts = counts[counts > 0].sort_values()
        if not counts.empty:
            fig, ax = plt.subplots(figsize=(8, max(4, 0.4 * len(counts))))
            ax.barh(counts.index.astype(str), counts.values, color='#8172B2')
            ax.set_title('Deal-structure mechanism frequency (dynamically discovered structure_has_* columns)')
            fig.tight_layout()
            fig.savefig(figures_dir / 'structure_mechanisms.png', dpi=150)
            plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description='Part 1: data exploration & visualization for Japan.csv')
    parser.add_argument('--input', type=Path, default=REPO_ROOT / 'data' / 'Japan.csv')
    parser.add_argument('--output-dir', type=Path, default=REPO_ROOT / 'output')
    args = parser.parse_args()

    df = load_data(args.input)

    figures_dir = args.output_dir / 'figures'
    reports_dir = args.output_dir / 'reports'
    reports_dir.mkdir(parents=True, exist_ok=True)

    make_visualizations(df, figures_dir)

    report = build_data_quality_report(df)
    report_path = reports_dir / 'data_quality.md'
    report_path.write_text(report, encoding='utf-8')

    print(f"Loaded {len(df)} rows from {args.input}")
    print(f"Wrote data quality report to {report_path}")
    print(f"Wrote figures to {figures_dir}")


if __name__ == '__main__':
    main()
